# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adbtool.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(945, 962)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(509, 600))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        MainWindow.setFont(font)
        MainWindow.setAcceptDrops(True)
        MainWindow.setStyleSheet("QPushbutton{\n"
"    background-color:#4682b4;\n"
"    color:shite;\n"
"}\n"
"")
        MainWindow.setIconSize(QtCore.QSize(16, 16))
        MainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.RefreshButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RefreshButton.sizePolicy().hasHeightForWidth())
        self.RefreshButton.setSizePolicy(sizePolicy)
        self.RefreshButton.setMinimumSize(QtCore.QSize(160, 35))
        self.RefreshButton.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.RefreshButton.setFont(font)
        self.RefreshButton.setObjectName("RefreshButton")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.RefreshButton)
        self.ComboxButton = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboxButton.sizePolicy().hasHeightForWidth())
        self.ComboxButton.setSizePolicy(sizePolicy)
        self.ComboxButton.setMinimumSize(QtCore.QSize(0, 35))
        self.ComboxButton.setMaximumSize(QtCore.QSize(16777215, 35))
        self.ComboxButton.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.ComboxButton.setFont(font)
        self.ComboxButton.setEditable(False)
        self.ComboxButton.setCurrentText("请点击刷新设备")
        self.ComboxButton.setMaxVisibleItems(60)
        self.ComboxButton.setIconSize(QtCore.QSize(16, 16))
        self.ComboxButton.setFrame(False)
        self.ComboxButton.setProperty("placeholderText", "")
        self.ComboxButton.setObjectName("ComboxButton")
        self.ComboxButton.addItem("")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ComboxButton)
        self.verticalLayout_3.addLayout(self.formLayout_3)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setObjectName("tabWidget")
        self.ADB = QtWidgets.QWidget()
        self.ADB.setObjectName("ADB")
        self.formLayout_5 = QtWidgets.QFormLayout(self.ADB)
        self.formLayout_5.setObjectName("formLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.Findstr = QtWidgets.QTextEdit(self.ADB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Findstr.sizePolicy().hasHeightForWidth())
        self.Findstr.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.Findstr.setFont(font)
        self.Findstr.setObjectName("Findstr")
        self.gridLayout.addWidget(self.Findstr, 4, 1, 1, 1)
        self.adbbutton = QtWidgets.QPushButton(self.ADB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.adbbutton.sizePolicy().hasHeightForWidth())
        self.adbbutton.setSizePolicy(sizePolicy)
        self.adbbutton.setMinimumSize(QtCore.QSize(0, 0))
        self.adbbutton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.adbbutton.setFont(font)
        self.adbbutton.setObjectName("adbbutton")
        self.gridLayout.addWidget(self.adbbutton, 3, 0, 1, 1)
        self.simulate_long_press_button = QtWidgets.QPushButton(self.ADB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.simulate_long_press_button.sizePolicy().hasHeightForWidth())
        self.simulate_long_press_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.simulate_long_press_button.setFont(font)
        self.simulate_long_press_button.setObjectName("simulate_long_press_button")
        self.gridLayout.addWidget(self.simulate_long_press_button, 8, 0, 1, 1)
        self.simulate_click_button = QtWidgets.QPushButton(self.ADB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.simulate_click_button.sizePolicy().hasHeightForWidth())
        self.simulate_click_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.simulate_click_button.setFont(font)
        self.simulate_click_button.setObjectName("simulate_click_button")
        self.gridLayout.addWidget(self.simulate_click_button, 8, 1, 1, 1)
        self.list_package_button = QtWidgets.QPushButton(self.ADB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_package_button.sizePolicy().hasHeightForWidth())
        self.list_package_button.setSizePolicy(sizePolicy)
        self.list_package_button.setMinimumSize(QtCore.QSize(0, 0))
        self.list_package_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.list_package_button.setFont(font)
        self.list_package_button.setObjectName("list_package_button")
        self.gridLayout.addWidget(self.list_package_button, 4, 0, 1, 1)
        self.adb_push_file_button = QtWidgets.QPushButton(self.ADB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.adb_push_file_button.sizePolicy().hasHeightForWidth())
        self.adb_push_file_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.adb_push_file_button.setFont(font)
        self.adb_push_file_button.setObjectName("adb_push_file_button")
        self.gridLayout.addWidget(self.adb_push_file_button, 6, 1, 1, 1)
        self.adb_uninstall_button = QtWidgets.QPushButton(self.ADB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.adb_uninstall_button.sizePolicy().hasHeightForWidth())
        self.adb_uninstall_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.adb_uninstall_button.setFont(font)
        self.adb_uninstall_button.setObjectName("adb_uninstall_button")
        self.gridLayout.addWidget(self.adb_uninstall_button, 7, 0, 1, 1)
        self.adb_pull_file_button = QtWidgets.QPushButton(self.ADB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.adb_pull_file_button.sizePolicy().hasHeightForWidth())
        self.adb_pull_file_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.adb_pull_file_button.setFont(font)
        self.adb_pull_file_button.setObjectName("adb_pull_file_button")
        self.gridLayout.addWidget(self.adb_pull_file_button, 3, 1, 1, 1)
        self.start_app = QtWidgets.QPushButton(self.ADB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_app.sizePolicy().hasHeightForWidth())
        self.start_app.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.start_app.setFont(font)
        self.start_app.setObjectName("start_app")
        self.gridLayout.addWidget(self.start_app, 7, 1, 1, 1)
        self.adb_install_button = QtWidgets.QPushButton(self.ADB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.adb_install_button.sizePolicy().hasHeightForWidth())
        self.adb_install_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.adb_install_button.setFont(font)
        self.adb_install_button.setObjectName("adb_install_button")
        self.gridLayout.addWidget(self.adb_install_button, 6, 0, 1, 1)
        self.adb_root_button = QtWidgets.QPushButton(self.ADB)
        self.adb_root_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.adb_root_button.sizePolicy().hasHeightForWidth())
        self.adb_root_button.setSizePolicy(sizePolicy)
        self.adb_root_button.setMinimumSize(QtCore.QSize(0, 0))
        self.adb_root_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.adb_root_button.setSizeIncrement(QtCore.QSize(0, 1))
        self.adb_root_button.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.adb_root_button.setFont(font)
        self.adb_root_button.setObjectName("adb_root_button")
        self.gridLayout.addWidget(self.adb_root_button, 1, 0, 1, 1)
        self.button_reboot = QtWidgets.QPushButton(self.ADB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_reboot.sizePolicy().hasHeightForWidth())
        self.button_reboot.setSizePolicy(sizePolicy)
        self.button_reboot.setMinimumSize(QtCore.QSize(0, 0))
        self.button_reboot.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.button_reboot.setFont(font)
        self.button_reboot.setToolTip("")
        self.button_reboot.setObjectName("button_reboot")
        self.gridLayout.addWidget(self.button_reboot, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.get_screenshot_button = QtWidgets.QPushButton(self.ADB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.get_screenshot_button.sizePolicy().hasHeightForWidth())
        self.get_screenshot_button.setSizePolicy(sizePolicy)
        self.get_screenshot_button.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.get_screenshot_button.setFont(font)
        self.get_screenshot_button.setObjectName("get_screenshot_button")
        self.gridLayout_2.addWidget(self.get_screenshot_button, 1, 0, 1, 1)
        self.view_apk_path = QtWidgets.QPushButton(self.ADB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.view_apk_path.sizePolicy().hasHeightForWidth())
        self.view_apk_path.setSizePolicy(sizePolicy)
        self.view_apk_path.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.view_apk_path.setFont(font)
        self.view_apk_path.setDefault(False)
        self.view_apk_path.setObjectName("view_apk_path")
        self.gridLayout_2.addWidget(self.view_apk_path, 1, 1, 1, 1)
        self.input_text_via_adb_button = QtWidgets.QPushButton(self.ADB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.input_text_via_adb_button.sizePolicy().hasHeightForWidth())
        self.input_text_via_adb_button.setSizePolicy(sizePolicy)
        self.input_text_via_adb_button.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.input_text_via_adb_button.setFont(font)
        self.input_text_via_adb_button.setObjectName("input_text_via_adb_button")
        self.gridLayout_2.addWidget(self.input_text_via_adb_button, 2, 0, 1, 1)
        self.get_running_app_info_button = QtWidgets.QPushButton(self.ADB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.get_running_app_info_button.sizePolicy().hasHeightForWidth())
        self.get_running_app_info_button.setSizePolicy(sizePolicy)
        self.get_running_app_info_button.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.get_running_app_info_button.setFont(font)
        self.get_running_app_info_button.setObjectName("get_running_app_info_button")
        self.gridLayout_2.addWidget(self.get_running_app_info_button, 2, 1, 1, 1)
        self.pull_log_without_clear = QtWidgets.QPushButton(self.ADB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pull_log_without_clear.sizePolicy().hasHeightForWidth())
        self.pull_log_without_clear.setSizePolicy(sizePolicy)
        self.pull_log_without_clear.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.pull_log_without_clear.setFont(font)
        self.pull_log_without_clear.setObjectName("pull_log_without_clear")
        self.gridLayout_2.addWidget(self.pull_log_without_clear, 3, 0, 1, 1)
        self.aapt_getpackagename_button = QtWidgets.QPushButton(self.ADB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.aapt_getpackagename_button.sizePolicy().hasHeightForWidth())
        self.aapt_getpackagename_button.setSizePolicy(sizePolicy)
        self.aapt_getpackagename_button.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.aapt_getpackagename_button.setFont(font)
        self.aapt_getpackagename_button.setObjectName("aapt_getpackagename_button")
        self.gridLayout_2.addWidget(self.aapt_getpackagename_button, 3, 1, 1, 1)
        self.pull_log_with_clear_button = QtWidgets.QPushButton(self.ADB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pull_log_with_clear_button.sizePolicy().hasHeightForWidth())
        self.pull_log_with_clear_button.setSizePolicy(sizePolicy)
        self.pull_log_with_clear_button.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.pull_log_with_clear_button.setFont(font)
        self.pull_log_with_clear_button.setObjectName("pull_log_with_clear_button")
        self.gridLayout_2.addWidget(self.pull_log_with_clear_button, 4, 0, 1, 1)
        self.clear_app_cache_button = QtWidgets.QPushButton(self.ADB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.clear_app_cache_button.sizePolicy().hasHeightForWidth())
        self.clear_app_cache_button.setSizePolicy(sizePolicy)
        self.clear_app_cache_button.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.clear_app_cache_button.setFont(font)
        self.clear_app_cache_button.setObjectName("clear_app_cache_button")
        self.gridLayout_2.addWidget(self.clear_app_cache_button, 4, 1, 1, 1)
        self.app_package_and_activity = QtWidgets.QPushButton(self.ADB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.app_package_and_activity.sizePolicy().hasHeightForWidth())
        self.app_package_and_activity.setSizePolicy(sizePolicy)
        self.app_package_and_activity.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.app_package_and_activity.setFont(font)
        self.app_package_and_activity.setObjectName("app_package_and_activity")
        self.gridLayout_2.addWidget(self.app_package_and_activity, 5, 0, 1, 1)
        self.force_stop_app = QtWidgets.QPushButton(self.ADB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.force_stop_app.sizePolicy().hasHeightForWidth())
        self.force_stop_app.setSizePolicy(sizePolicy)
        self.force_stop_app.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.force_stop_app.setFont(font)
        self.force_stop_app.setObjectName("force_stop_app")
        self.gridLayout_2.addWidget(self.force_stop_app, 5, 1, 1, 1)
        self.close = QtWidgets.QPushButton(self.ADB)
        self.close.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.close.sizePolicy().hasHeightForWidth())
        self.close.setSizePolicy(sizePolicy)
        self.close.setMinimumSize(QtCore.QSize(0, 0))
        self.close.setMaximumSize(QtCore.QSize(16777215, 83))
        self.close.setBaseSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.close.setFont(font)
        self.close.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.close.setMouseTracking(False)
        self.close.setTabletTracking(False)
        self.close.setAcceptDrops(False)
        self.close.setCheckable(False)
        self.close.setAutoDefault(False)
        self.close.setDefault(False)
        self.close.setFlat(False)
        self.close.setObjectName("close")
        self.gridLayout_2.addWidget(self.close, 0, 0, 1, 2)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.formLayout_5.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.gridLayout_3)
        self.tabWidget.addTab(self.ADB, "")
        self.ADB_02 = QtWidgets.QWidget()
        self.ADB_02.setEnabled(True)
        self.ADB_02.setObjectName("ADB_02")
        self.formLayout_2 = QtWidgets.QFormLayout(self.ADB_02)
        self.formLayout_2.setObjectName("formLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.switch_vr_env_button = QtWidgets.QPushButton(self.ADB_02)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.switch_vr_env_button.sizePolicy().hasHeightForWidth())
        self.switch_vr_env_button.setSizePolicy(sizePolicy)
        self.switch_vr_env_button.setMinimumSize(QtCore.QSize(170, 50))
        self.switch_vr_env_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.switch_vr_env_button.setFont(font)
        self.switch_vr_env_button.setObjectName("switch_vr_env_button")
        self.verticalLayout.addWidget(self.switch_vr_env_button)
        self.VR_nework_check_button = QtWidgets.QPushButton(self.ADB_02)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VR_nework_check_button.sizePolicy().hasHeightForWidth())
        self.VR_nework_check_button.setSizePolicy(sizePolicy)
        self.VR_nework_check_button.setMinimumSize(QtCore.QSize(170, 0))
        self.VR_nework_check_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.VR_nework_check_button.setFont(font)
        self.VR_nework_check_button.setObjectName("VR_nework_check_button")
        self.verticalLayout.addWidget(self.VR_nework_check_button)
        self.activate_VR_button = QtWidgets.QPushButton(self.ADB_02)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.activate_VR_button.sizePolicy().hasHeightForWidth())
        self.activate_VR_button.setSizePolicy(sizePolicy)
        self.activate_VR_button.setMinimumSize(QtCore.QSize(170, 0))
        self.activate_VR_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.activate_VR_button.setFont(font)
        self.activate_VR_button.setObjectName("activate_VR_button")
        self.verticalLayout.addWidget(self.activate_VR_button)
        self.enter_engineering_mode_button = QtWidgets.QPushButton(self.ADB_02)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enter_engineering_mode_button.sizePolicy().hasHeightForWidth())
        self.enter_engineering_mode_button.setSizePolicy(sizePolicy)
        self.enter_engineering_mode_button.setMinimumSize(QtCore.QSize(170, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.enter_engineering_mode_button.setFont(font)
        self.enter_engineering_mode_button.setObjectName("enter_engineering_mode_button")
        self.verticalLayout.addWidget(self.enter_engineering_mode_button)
        self.upgrade_page_button_2 = QtWidgets.QPushButton(self.ADB_02)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upgrade_page_button_2.sizePolicy().hasHeightForWidth())
        self.upgrade_page_button_2.setSizePolicy(sizePolicy)
        self.upgrade_page_button_2.setMinimumSize(QtCore.QSize(170, 0))
        self.upgrade_page_button_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.upgrade_page_button_2.setFont(font)
        self.upgrade_page_button_2.setObjectName("upgrade_page_button_2")
        self.verticalLayout.addWidget(self.upgrade_page_button_2)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout)
        self.tabWidget.addTab(self.ADB_02, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(15, 15, 321, 281))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.upgrade_page_button = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upgrade_page_button.sizePolicy().hasHeightForWidth())
        self.upgrade_page_button.setSizePolicy(sizePolicy)
        self.upgrade_page_button.setMinimumSize(QtCore.QSize(200, 70))
        self.upgrade_page_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.upgrade_page_button.setFont(font)
        self.upgrade_page_button.setObjectName("upgrade_page_button")
        self.verticalLayout_2.addWidget(self.upgrade_page_button)
        self.skipping_powerlimit_button = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skipping_powerlimit_button.sizePolicy().hasHeightForWidth())
        self.skipping_powerlimit_button.setSizePolicy(sizePolicy)
        self.skipping_powerlimit_button.setMinimumSize(QtCore.QSize(200, 0))
        self.skipping_powerlimit_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.skipping_powerlimit_button.setFont(font)
        self.skipping_powerlimit_button.setCheckable(False)
        self.skipping_powerlimit_button.setAutoDefault(False)
        self.skipping_powerlimit_button.setObjectName("skipping_powerlimit_button")
        self.verticalLayout_2.addWidget(self.skipping_powerlimit_button)
        self.AS33_CR_enter_engineering_mode_button = QtWidgets.QPushButton(self.widget)
        self.AS33_CR_enter_engineering_mode_button.setMinimumSize(QtCore.QSize(200, 70))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.AS33_CR_enter_engineering_mode_button.setFont(font)
        self.AS33_CR_enter_engineering_mode_button.setObjectName("AS33_CR_enter_engineering_mode_button")
        self.verticalLayout_2.addWidget(self.AS33_CR_enter_engineering_mode_button)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.widget1 = QtWidgets.QWidget(self.tab_2)
        self.widget1.setGeometry(QtCore.QRect(15, 15, 291, 181))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.MZS3E_TT_enter_engineering_mode_button = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MZS3E_TT_enter_engineering_mode_button.sizePolicy().hasHeightForWidth())
        self.MZS3E_TT_enter_engineering_mode_button.setSizePolicy(sizePolicy)
        self.MZS3E_TT_enter_engineering_mode_button.setMinimumSize(QtCore.QSize(170, 70))
        self.MZS3E_TT_enter_engineering_mode_button.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.MZS3E_TT_enter_engineering_mode_button.setFont(font)
        self.MZS3E_TT_enter_engineering_mode_button.setCheckable(False)
        self.MZS3E_TT_enter_engineering_mode_button.setAutoDefault(False)
        self.MZS3E_TT_enter_engineering_mode_button.setObjectName("MZS3E_TT_enter_engineering_mode_button")
        self.verticalLayout_4.addWidget(self.MZS3E_TT_enter_engineering_mode_button)
        self.MZS3E_TT = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MZS3E_TT.sizePolicy().hasHeightForWidth())
        self.MZS3E_TT.setSizePolicy(sizePolicy)
        self.MZS3E_TT.setMinimumSize(QtCore.QSize(170, 70))
        self.MZS3E_TT.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.MZS3E_TT.setFont(font)
        self.MZS3E_TT.setObjectName("MZS3E_TT")
        self.verticalLayout_4.addWidget(self.MZS3E_TT)
        self.tabWidget.addTab(self.tab_2, "")
        self.text = QtWidgets.QWidget()
        self.text.setObjectName("text")
        self.formLayout = QtWidgets.QFormLayout(self.text)
        self.formLayout.setObjectName("formLayout")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.text)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(16)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setAcceptDrops(False)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.textBrowser_2)
        self.tabWidget.addTab(self.text, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(14)
        self.textBrowser.setFont(font)
        self.textBrowser.setAcceptDrops(True)
        self.textBrowser.setTabChangesFocus(False)
        self.textBrowser.setReadOnly(False)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_3.addWidget(self.textBrowser)
        self.Cleartextbutton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Cleartextbutton.sizePolicy().hasHeightForWidth())
        self.Cleartextbutton.setSizePolicy(sizePolicy)
        self.Cleartextbutton.setMinimumSize(QtCore.QSize(0, 40))
        self.Cleartextbutton.setObjectName("Cleartextbutton")
        self.verticalLayout_3.addWidget(self.Cleartextbutton)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(398, 28))
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.ComboxButton.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.Cleartextbutton.clicked.connect(self.textBrowser.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ADBTools"))
        self.RefreshButton.setText(_translate("MainWindow", "刷新设备"))
        self.ComboxButton.setItemText(0, _translate("MainWindow", "请点击刷新设备"))
        self.adbbutton.setText(_translate("MainWindow", "执行adb"))
        self.simulate_long_press_button.setText(_translate("MainWindow", "模拟长按"))
        self.simulate_click_button.setText(_translate("MainWindow", "模拟点击"))
        self.list_package_button.setText(_translate("MainWindow", "列出所有包名"))
        self.adb_push_file_button.setText(_translate("MainWindow", "Push文件"))
        self.adb_uninstall_button.setText(_translate("MainWindow", "卸载应用"))
        self.adb_pull_file_button.setText(_translate("MainWindow", "Pull文件"))
        self.start_app.setText(_translate("MainWindow", "启动应用"))
        self.adb_install_button.setText(_translate("MainWindow", "安装应用"))
        self.adb_root_button.setText(_translate("MainWindow", "获取Root权限"))
        self.button_reboot.setText(_translate("MainWindow", "重启设备"))
        self.get_screenshot_button.setText(_translate("MainWindow", "Screen"))
        self.view_apk_path.setText(_translate("MainWindow", "adb shell pm path"))
        self.input_text_via_adb_button.setText(_translate("MainWindow", "Input text"))
        self.get_running_app_info_button.setText(_translate("MainWindow", "获取应用版本号"))
        self.pull_log_without_clear.setText(_translate("MainWindow", "Pull all log"))
        self.aapt_getpackagename_button.setText(_translate("MainWindow", "获取apk文件的包名"))
        self.pull_log_with_clear_button.setText(_translate("MainWindow", "Clear-Pull log"))
        self.clear_app_cache_button.setText(_translate("MainWindow", "Clear App 缓存"))
        self.app_package_and_activity.setText(_translate("MainWindow", "获取包名和活动页名"))
        self.force_stop_app.setText(_translate("MainWindow", "Close App"))
        self.close.setText(_translate("MainWindow", "关闭"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ADB), _translate("MainWindow", "ADB"))
        self.switch_vr_env_button.setText(_translate("MainWindow", "切换VR环境"))
        self.VR_nework_check_button.setText(_translate("MainWindow", "VR网络环境检查"))
        self.activate_VR_button.setText(_translate("MainWindow", "调起VR"))
        self.enter_engineering_mode_button.setText(_translate("MainWindow", "进入工程模式"))
        self.upgrade_page_button_2.setText(_translate("MainWindow", "调起延峰升级页面"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ADB_02), _translate("MainWindow", "IS31项目"))
        self.upgrade_page_button.setText(_translate("MainWindow", "调起延峰升级页面"))
        self.skipping_powerlimit_button.setText(_translate("MainWindow", "跳过升级时的电源\n"
"模式与挡位限制"))
        self.AS33_CR_enter_engineering_mode_button.setText(_translate("MainWindow", "AS33_CR进入工程模式"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "AS33/ASSP项目"))
        self.MZS3E_TT_enter_engineering_mode_button.setText(_translate("MainWindow", "进入工程模式"))
        self.MZS3E_TT.setText(_translate("MainWindow", "调起延峰升级页面"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "MZS3E_TT项目"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Franklin Gothic Medium\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">adb root</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">adb remount remount</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">adb shell &quot;setprop bmi.service.adb.root 1&quot;</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.text), _translate("MainWindow", "TEXT"))
        self.Cleartextbutton.setText(_translate("MainWindow", "清空"))
        self.label.setText(_translate("MainWindow", "作者：王克    微信：2315313745"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

